# Utiliser la dernière version d'Ubuntu comme image de base
FROM ubuntu:latest

# Mettre à jour les listes de paquets APT
RUN apt-get update

# Mettre à jour tous les logiciels installés
RUN apt-get upgrade -y

# Définir une commande pour afficher "Hello, World!" lorsque le conteneur est exécuté
CMD echo "Hello, World!"
